# Generated by Django 3.1.2 on 2020-10-06 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('note', '0002_auto_20201004_1707'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='note',
            options={'ordering': ('modified',)},
        ),
    ]
