# Generated by Django 3.1.2 on 2020-10-05 06:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weathernote', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Note',
            new_name='NoteW',
        ),
    ]
