# Generated by Django 3.1.2 on 2020-10-05 08:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weathernote', '0002_auto_20201005_0839'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NoteW',
        ),
    ]
